### ISSUE TITLE
Unable to install on MacOS Big Sur

### ISSUE THREAD

**Issue by reskin89** [graphp/graphviz#55] opened 2021-05-10 13:49 UTC
Currently on Big Sur, attempting to brew install results in:

`Error: Interrupted system call @ rb_sysopen - /usr/local/Cellar/webp/1.2.0/bin/webpinfo`

It seems to be a common issue on big sur.  Is there a good way around this?

**Comment by clue** [comment] 2021-05-13 17:33
Closed as duplicate of #54.

**Closed by clue** 2021-05-13 17:33 UTC
Labels: invalid
